[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.14"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v11.0.0"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "9316a62528ac99aaecb4e47eadd6dc8aa6533d58"

[prune]
  go-tests = true
  unused-packages = true
