apiVersion: v1
kind: ServiceAccount
metadata:
  name: networkpolicy-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: networkpolicy-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkpolicy-controller
  labels:
    app.kubernetes.io/name: networkpolicy-controller
rules:
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - update
  - create
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: networkpolicy-controller
  labels:
    app.kubernetes.io/name: networkpolicy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: networkpolicy-controller
subjects:
- kind: ServiceAccount
  name: networkpolicy-controller
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkpolicy-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: networkpolicy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: networkpolicy-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: networkpolicy-controller
    spec:
      serviceAccountName: networkpolicy-controller
      containers:
      - name: networkpolicy-controller
        image: elisaoyj/networkpolicy-controller:latest
