ignoreAnnotation: networkpolicy.elisa.fi
rules:
- ignoredNamespaces:
  - kube-system
  spec:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-all-except-metadata
    spec:
      podSelector: {}
      egress:
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except: 
            - 169.254.169.254/32
      policyTypes:
      - Egress
